name: ComeSano
options:
  minimumXcodeGenVersion: 2.44.1
  deploymentTarget:
    iOS: "17.0"
packages:
  ComeSanoPackage:
    path: .
settings:
  base:
    SWIFT_VERSION: "6.0"
    PRODUCT_BUNDLE_IDENTIFIER: rcTools.ComeSano
targets:
  ComeSanoApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App/Sources
    resources:
      - path: App/Resources
    settings:
      base:
        INFOPLIST_FILE: App/Config/Info.plist
        PRODUCT_NAME: ComeSano
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: ComeSanoPackage
        product: ComeSanoCore
      - package: ComeSanoPackage
        product: ComeSanoAI
      - package: ComeSanoPackage
        product: ComeSanoUI
schemes:
  ComeSanoApp:
    build:
      targets:
        ComeSanoApp: all
    run:
      config: Debug
    archive:
      config: Release
